actimes:
  actimes:
    - date: 2014年7月
      title: 文発活動報告
      url: actimes-2014-07.pdf
      img: actimes-2014-07.png

    - date: 2013年10月
      title: 球技大会
      url: actimes-2013-10.pdf
      img: actimes-2013-10.png

    - date: 2013年6月
      title: 文化発表会
      url: actimes-2013-06.pdf
      img: actimes-2013-06.png

    - date: 2013年4月
      title: ご入学おめでとうございます！
      url: actimes-2013-04.pdf
      img: actimes-2013-04.png
