news:
  articles:
    - date: 2015.07.11
      title: 第◯回 文化発表会を開催しました！
      content: |-
        <p>
          高校入学を機に木組みの家と石畳の街に引っ越してきたココアは、下宿先を探して道に迷う中、<strong>ラビットハウス</strong>という名の喫茶店を発見する。
          <a href="http://dic.nicovideo.jp/a/%E3%83%86%E3%82%A3%E3%83%83%E3%83%94%E3%83%BC">ティッピー</a>というモフモフとしたうさぎだった。
          コーヒーを飲みながら、下宿先の場所を尋ねるココアであったが、なんとラビットハウスこそが自分の探す下宿先であることが判明。
          お世話になる家に奉仕をするという高校の方針から、ココアはラビットハウスの店員として、そしてチノの“自称”姉として働くことになるのだった。
        </p>
        <p>
          高校入学を機に木組みの家と石畳の街に引っ越してきたココアは、下宿先を探して道に迷う中、ラビットハウスという名の喫茶店を発見する。
          名前からうさぎだらけの喫茶店に違いないと思ったココアであったが、そこにいたのはチノという小さな少女と、ティッピーというモフモフとしたうさぎだった。
          コーヒーを飲みながら、下宿先の場所を尋ねるココアであったが、なんとラビットハウスこそが自分の探す下宿先であることが判明。
          お世話になる家に奉仕をするという高校の方針から、ココアはラビットハウスの店員として、そしてチノの“自称”姉として働くことになるのだった。
        </p>
        <p>
          高校入学を機に木組みの家と石畳の街に引っ越してきたココアは、下宿先を探して道に迷う中、ラビットハウスという名の喫茶店を発見する。
          名前からうさぎだらけの喫茶店に違いないと思ったココアであったが、そこにいたのはチノという小さな少女と、ティッピーというモフモフとしたうさぎだった。
          コーヒーを飲みながら、下宿先の場所を尋ねるココアであったが、なんとラビットハウスこそが自分の探す下宿先であることが判明。
          お世話になる家に奉仕をするという高校の方針から、ココアはラビットハウスの店員として、そしてチノの“自称”姉として働くことになるのだった。
        </p>
    - date: 2015.04.25
      title: お葉見に行ってきました
      content: |-
        たのしかった！＼(^o^)／
    - date: 2015.04.01
      title: 新年度が始まりました
      content: |-
        ＼(^o^)／
    - date: 2015.06.24
      title: ほげほげ
      content: |-
        <code>rake generate_news[ほげほげ]</code>を使って投稿できた！！
